on: push

jobs:
  update-registry:
    runs-on: ubuntu-latest
    outputs:
      head: ${{ steps.ls-crates-io-index.outputs.head }}
    steps:
      - uses: actions/checkout@v2

      - id: ls-crates-io-index
        name: Get head commit hash of crates.io registry index
        run: |
          commit=$(
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
            cut -f 1
          )
          echo "::set-output name=head::$commit"
      - name: Cache cargo registry index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ steps.ls-crates-io-index.outputs.head }}
          restore-keys: cargo-index-

      - run: cargo fetch

  build:
    needs: update-registry
    strategy:
      matrix:
        build: [a, b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Restore cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ needs.update-registry.outputs.head }}

      - name: Build the binaries
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -C prefer-dynamic=yes
          CARGO_INCREMENTAL: 0
        with:
          command: build
          args: >
            --target-dir target-${{ matrix.build }}
            --verbose --release
            --lib --bin hello-world

      - name: Dump information from binaries
        run: |
          set -x
          ls -l target-${{ matrix.build }}/release target-${{ matrix.build }}/release/deps
          mkdir elf-info
          readelf -a -D -W target-${{ matrix.build }}/release/libhello_world.so > elf-info/dylib-${{ matrix.build }}.txt
          readelf -a -D -W target-${{ matrix.build }}/release/hello-world > elf-info/bin-${{ matrix.build }}.txt ||:

      - uses: actions/upload-artifact@v2
        with:
          path: elf-info
