name: Check for leftover files in Cargo registry cache

on: push

jobs:
  list-on-windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: List Cargo registry cache files
        run: Get-ChildItem $env:UserProfile\.cargo\registry -Recurse
      - name: Clean up cargo registry files
        run: rm -r -fo $env:UserProfile\.cargo\registry

  cleanup-on-windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Clean up cargo registry files on cold state
        run: rm -r -fo $env:UserProfile\.cargo\registry

  list-on-linux:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: List Cargo registry cache files
        run: ls -lR ~/.cargo/registry

  list-on-mac:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: List Cargo registry cache files
        run: ls -lR ~/.cargo/registry
