name: Check for leftover files in Cargo registry cache

on: push

jobs:
  list-on-windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: List Cargo registry cache files
        run: Get-ChildItem $env:UserProfile\.cargo\registry -Recurse

  list-on-linux:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: List Cargo registry cache files
        run: ls -lR ~/.cargo/registry
