on:
  push:
    tags:
      - 'test-release-v*'

name: Two-stage release creation

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} (in progress)
          draft: true
      - name: Pause
        run: |
          echo 'Check it out at ${{ steps.create_release.outputs.html_url }},'
          echo 'release ${{ steps.create_release.outputs.id }} is now in draft!'
          sleep 60
      - name: Publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
