on:
  push:
    tags:
      - 'test-release-v*'

name: Two-stage release creation

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Create release draft
        id: create_release
        run: |
          release_ver=${GITHUB_REF#refs/tags/}
          hub release create --draft \
            -m "Release $release_ver (in progress)" \
            $release_ver
          upload_url=$(hub release show -f '%uA' $release_ver)
          echo "::set-output name=upload_url::$upload_url"

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./README.md
          asset_name: README.md
          asset_content_type: text/markdown

      - name: Publish release
        run: |
          release_ver=${GITHUB_REF#refs/tags/}
          hub release edit --draft=false \
            -m "Release $release_ver" \
            $release_ver

