on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Print tar info
        run: |
          which tar
          tar --version

      - name: Copy and checksum binaries
        run: |
          mkdir target
          cp -p /Library/Developer/CommandLineTools/usr/bin/{clang,ld} target/
          shasum target/* > checksum

      - name: Archive
        run: |
          tar -C target -czvf archive.tar.gz clang ld
          rm -rf target

      - name: Extract binaries from the archive
        run: |
          mkdir target
          tar -C target -xzvf archive.tar.gz

      - name: Verify the checksum
        run: shasum -c checksum
