on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --release
            --locked
            --verbose

      - name: Archive
        run: |
          tar -C ./target/release -czvf archive.tar.gz github-actions-playground

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: archive.tar.gz
