on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Print tar info
        run: |
          which tar
          tar --version

      - name: Copy and checksum binary
        run: |
          mkdir target
          cp -p /bin/bash target/
          shasum target/bash > checksum

      - name: Archive
        run: |
          tar -C target -czvf archive.tar.gz bash
          rm -rf target

      - uses: actions/upload-artifact@v2
        with:
          path: archive.tar.gz

      - name: Extract binary from the archive
        run: |
          mkdir target
          tar -C target -xzvf archive.tar.gz

      - name: Verify the checksum
        run: shasum -c checksum
