on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: diskutil info -all

      - uses: actions/checkout@v2

      - name: Install the stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --verbose

      - name: Checksum the binary
        run: |
          shasum target/debug/github-actions-playground > ${{ runner.temp }}/checksum

      - name: Archive
        run: |
          tar -C target/debug -czvf ${{ runner.temp }}/archive.tar.gz github-actions-playground

      - name: Extract the archive
        run: |
          rm -r target/debug/*
          tar -C target/debug -xzvf ${{ runner.temp }}/archive.tar.gz

      - name: Verify the checksum
        run: shasum -c ${{ runner.temp }}/checksum
