on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print tar info, pristine environment
        run: |
          which tar
          tar --version

      - if: ${{ runner.os == 'macOS' }}
        name: Augment PATH with install location of GNU tar binary
        run: |
          echo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV

      - if: ${{ runner.os == 'macOS' }}
        name: Print tar info, PATH modified for GNU tar
        run: |
          which tar
          tar --version

      - name: Archive
        run: |
          tar -C /bin -czvf archive.tar.gz bash

      - uses: actions/upload-artifact@v2
        with:
          name: tarball-${{ matrix.os }}
          path: archive.tar.gz
